cicd - improvements

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -1,40 +1,83 @@
-# see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven
+# Build, test a Maven project and release as Docker image.
+## see: https://docs.github.com/en/actions/tutorials/build-and-test-code/java-with-maven
+## see: https://docs.github.com/en/actions/tutorials/publish-packages/publish-docker-images
 
-name: Java CI with Maven and Docker
+name: Java CI with Gradle and Docker
 
 on:
-  # Only on push to any branches or on publishing release tag
+  # Only on push to any branches or on tag
   push:
-    branches:
-    tags:
-      - 'v[0-9]+\.[0-9]+\.[0-9]+'
+    branches: ['**']
+    tags: ['v[0-9]+.[0-9]+.[0-9]+']
+
+  workflow_dispatch:
+    inputs:
+      manual_deploy:
+        description: "Trigger manual deployment"
+        required: true
+        type: choice
+        options:
+          - "false"
+          - "true"
+        default: "false"
 
 jobs:
-  build:
+  gradle-docker-build:
     runs-on: ubuntu-latest
 
     steps:
     - name: Checkout code
-      uses: actions/checkout@v4
+      uses: actions/checkout@v6
 
     - name: Set up JDK 25
-      uses: actions/setup-java@v4
+      uses: actions/setup-java@v5
       with:
         java-version: '25'
         distribution: 'temurin'
-        cache: maven
 
-    - name: Extract Gradle project version
-      id: project-version
+      # 1. Validate version against branch / release tag
+    - name: Validate Project Version
+      id: validate-project-version
+        env:
+          MANUAL_DEPLOY: ${{ inputs.manual_deploy }}
       run: |
         chmod +x ./gradlew
-        echo "project_version=$(./gradlew -q printVersion 2>/dev/null)" >> $GITHUB_OUTPUT
+        APP_VERSION=$(./gradlew -q printVersion 2>/dev/null)
+        echo "app_version=$APP_VERSION" >> "$GITHUB_OUTPUT"
+        echo "Event=$GITHUB_EVENT_NAME  Ref=$GITHUB_REF_NAME ($GITHUB_REF_TYPE)  Version=$APP_VERSION"
 
-    - name: Build with Gradle
+          # ---------- RELEASE RULE ----------
+          if [[ "$GITHUB_REF_TYPE" == "tag" ]]; then
+            if [[ "$APP_VERSION" == *-SNAPSHOT ]]; then
+              echo "❌ ERROR: Tagged version cannot be SNAPSHOT. Found: $APP_VERSION"
+              exit 1
+            fi
+            if [[ "${GITHUB_REF_NAME#v}" != "$APP_VERSION" ]]; then
+              echo "❌ ERROR: Tag ($GITHUB_REF_NAME) does NOT match pom version ($APP_VERSION)"
+              exit 1
+            fi
+
+      # 2. Compile
+    - name: Gradle Compile
       run: ./gradlew clean build
 
-    - name: Build the Docker image
-      if: github.ref_type == 'tag' && github.event.base_ref == 'refs/heads/main'
-      run: |
-        docker build . --file Dockerfile \
-          --tag muneer2ishtech/ishtech-springboot-books-app:${{ steps.project-version.outputs.project_version }}
+      # 3. Test
+      - name: Gradle Test
+        run: ./mvnw $MAVEN_CLI_OPTS test -Dmaven.main.skip=true
+
+      # 4. Release (only when conditions match)
+      - name: Login to Docker Hub
+        if: steps.validate-project-version.outputs.do_release == 'true'
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_PASSWORD }}
+
+      - name: Build and push Docker image
+        if: steps.validate-project-version.outputs.do_release == 'true'
+        uses: docker/build-push-action@v7
+        with:
+          context: .
+          file: ./Dockerfile
+          push: true
+          tags: muneer2ishtech/ishtech-springboot-books-app:${{ steps.validate-project-version.outputs.app_version }}
